name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install node dependencies
        run: |
          npm i -g pnpm
          pnpm i

      - name: Lint
        run: |
          pnpm run lint
          pnpm run check

      - name: Build
        run: |
          pnpm run build
          pnpm run build:harmony
          pnpm run build:preview

      - name: Test
        run: |
          npx playwright install chromium
          pnpm run test

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      - name: Release
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: harmony
          prerelease: true
          title: Harmony Build
          files: |
            dist/harmony/index.html
